stages:
  - deploy

deploy_development:
  image: alpine:latest
  stage: deploy
  environment:
    name: development
  only:
    - develop
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client git
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd $REPO_PATH && git pull $GIT_REPO $GIT_BRANCH && docker-compose -f $COMPOSE_PATH down && docker-compose -f $COMPOSE_PATH up --build -d"

deploy_staging:
  image: alpine:latest
  stage: deploy
  environment:
    name: staging
  only:
    - master
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client git
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd $REPO_PATH && git pull $GIT_REPO $GIT_BRANCH && docker-compose -f $COMPOSE_PATH down && docker-compose -f $COMPOSE_PATH up --build -d"
