version: '3.4'

services:
  mysql:
    image: mysql:8.0.26
    container_name: notaire_mysql_$NODE_ENV
    tty: true
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    command: --init-file /data/application/init.sql
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
      - ./db/init.sql:/data/application/init.sql
    cap_add:
      - SYS_NICE
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: notaire_pma_$NODE_ENV
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    ports:
      - $PMA_LOCAL_PORT:80
    restart: unless-stopped

  notaire_api:
    image: notaire_api
    container_name: notaire_api_$NODE_ENV
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    depends_on:
      - mysql
    environment:
      NODE_ENV: $NODE_ENV
      MYSQL_HOST: mysql
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    restart: unless-stopped

volumes:
  mysql:
  mysql_config:
